- name: Install Docker
  become: true
  community.general.pacman:
    name: [ "docker" ]
    state: present
  tags:
    - install
    - containers
    - docker

- name: Add User to Docker Group
  become: true
  shell: "usermod -aG docker { user }"
  tags:
    - install
    - containers
    - docker

- name: Install Docker
  become: true
  community.general.pacman:
    name: [ "qemu-full" ]
    state: present
  tags:
    - install
    - containers
    - qemu
