- name: Install System Packages 1 (base-devel, cmake, pkg-config)
  become: true
  community.general.pacman:
    name: ["base-devel", "cmake", "pkg-config"]
    state: present
  tags:
    - install
    - core
    - neovim

- name: Download Paru
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/paru.git"
    dest: "{{ home }}/paru"
  tags:
    - install
    - paru
- name: Install Paru
  shell: "cd {{ home }}/paru && makepkg -si --noconfirm"
  tags:
    - install
    - paru
- name: Cleanup Paru
  shell: "rm -Rf {{ home }}/paru"
  tags:
    - install
    - paru

- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  become: true
  community.general.pacman:
    name: [ "lua", "unzip", "libtool", "gettext"]
    state: present
  tags:
    - install
    - core
    - neovim

- name: Install System Packages 3 (the rest)
  become: true
  community.general.pacman:
    name: [ "curl", "htop", "ccache", "dconf-editor", "clang", "rust", "stow" ]
    state: present
  tags:
    - install
    - core
    - neovim

- name: Install System Packages 3 AUR (the rest)
  become: true
  community.general.pacman:
    executable: "paru"
    name: [ "ttf-hack-nerd", "ttf-sourcecodepro-nerd" ]
    state: present
  tags:
    - install
    - core
    - neovim

- name: Install WM (i3 + polybar + alactritty)
  become: true
  community.general.pacman:
    name: [ "i3-wm", "i3lock", "polybar", "htop", "dmenu", "alacritty", "feh", "picom", "rofi", "dunst" ]
    state: present
  tags:
    - install
    - core

- name: Install DM (ly)
  become: true
  community.general.pacman:
    executable: "paru"
    name: [ "ly" ]
    state: present
  tags:
    - install
    - core

- name: Enable DM (ly)
  become: true
  ansible.builtin.systemd:
    name: httpd
    enabled: true
  tags:
    - install
    - core
