- name: Install Android SDK
  become: true
  community.general.pacman:
    executable: "paru"
    name: [ "android-sdk-cmdline-tools-latest", "android-sdk-platform-tools", "android-udev" ]
    state: present
  tags:
    - install
    - mobile
    - android
