- name: Install Web Sofwate (Firefox, Thunderbird, Telegram)
  become: true
  community.general.pacman:
    name: [ "firefox", "thunderbird", "telegram-desktop" ]
    state: present
  tags:
    - install
    - core
    - software
    - web

- name: Install Web Software AUR (LibreWolf, Google Chrome, FreeTube, YewTume, Viber)
  become: true
  community.general.pacman:
    executable: "paru"
    name: [ "librewolf-bin", "google-chrome", "freetube-bin", "yewtube-git", "viber" ]
    state: present
  tags:
    - install
    - core
    - software
    - web

- name: Install Graphics Software (Gimp)
  become: true
  community.general.pacman:
    name: [ "gimp" ]
    state: present
  tags:
    - install
    - core
    - software
    - graphics

- name: Install Graphics Software AUR (OpenBoard)
  become: true
  community.general.pacman:
    executable: "paru"
    name: [ "openboard" ]
    state: present
  tags:
    - install
    - core
    - software
    - graphics
