- name: Notebooks
  file:
    path: "{{ notebooks }}"
    state: directory
  tags:
    - install
    - notebooks
    - notebooks-personal
    - notebooks-work

- name: Notebooks (personal)
  ansible.builtin.git:
    repo: "git@github.com:zivlakmilos/zk-nootebook-personal.git"
    dest: "{{ notebooks }}/personal"
  tags:
    - install
    - notebooks
    - notebooks-personal

- name: Notebooks (work)
  ansible.builtin.git:
    repo: "git@github.com:zivlakmilos/zk-nootebook-work.git"
    dest: "{{ notebooks }}/work"
  tags:
    - install
    - notebooks
    - notebooks-work
