#!/usr/bin/env bash

sudo pacman -S zsh exa neofetch xclip
sudo chsh -s $(which zsh)

curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh >$HOME/.oh-my-installer && chmod +x $HOME/oh-my-installer && $HOME/.oh-my-installer
$HOME/.oh-my-installer
git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/plugins/zsh-autosuggestions
