#!/usr/bin/env bash

# NeoVim
sudo pacman -S neovim lazygit ripgrep fd luarocks

# C
sudo pacman -S clang
sudo pacman -S gdb
paru -S gf2
sudo pacman -S gtk3 webkit2gtk

# Go
sudo pacman -S go
go install github.com/air-verse/air@latest
go install github.com/a-h/templ/cmd/templ@latest
go install github.com/wailsapp/wails/v2/cmd/wails@latest

# Node
sudo pacman -S nodejs npm

# Android SDK
paru -S android-sdk-cmdline-tools-latest android-sdk-platform-tools android-udev

# Containers
sudo pacman -S docker
sudo usermod -aG docker $USER

# VMs
sudo pacman -S qemu-full libvirt virt-manager
sudo usermod -a -G kvm $USER
sudo usermod -a -G libvirt $USER
sudo systemctl enable libvirtd.service
sudo systemctl start libvirtd.service

# Networking
sudo pacman -S tcpdump wireshark-qt
sudo usermod -a -G wireshark $USER

# Win
sudo pacman -S mingw-w64-binutils mingw-w64-gcc mingw-w64-crt mingw-w64-headers mingw-w64-winpthreads
paru -S nsis

# Other
sudo pacman -S cloc
paru -S bruno-bin postman-bin
