#!/usr/bin/env bash

# Web
sudo pacman -S firefox thunderbird telegram-desktop
paru -S librewolf-bin google-chrome freetube-bin yewtube-git viber slack-desktop yt-dlp
sudo pacman -S firefox thunderbird telegram-desktop

# Graphic
sudo pacman -S gimp
paru -S openboard

# Time management
paru -S timetrace-bin
go install github.com/rwxrob/pomo/cmd/pomo@latest

# Multimedia
sudo pacman -S obs-studio kdenlive
paru -S spotify

# Passwordss
sudo pacman -S keepassxc
