#!/usr/bin/env bash

sudo pacman -S zk

git clone git@github.com:zivlakmilos/zk-nootebook-personal.git $HOME/notebook/personal
git clone git@github.com:zivlakmilos/zk-nootebook-work.git $HOME/notebook/work
